[pytest]
testpaths = Tests

# Custom marker to identify tests that require actual hardware interaction, allowing us to easily include or exclude them when running tests
markers = 
    hardware: Tests mit echter Hardware (GPIO, Wallbox)

# Ignore warnings about deprecated features and user warnings that are not relevant to our tests,
# to keep the test output clean and focused on actual test results
filterwarnings = 
    ignore::DeprecationWarning
    ignore::UserWarning

# Disable pytest's cache provider to prevent it from trying to write cache files during tests,
# which can cause issues in certain environments and is not needed for our test suite
addopts = -p no:cacheprovider